### ISSUE TITLE
Path separater is "wrong" on Windows

### ISSUE THREAD

**Issue by erikbra** [benaadams/Ben.Demystifier#65] opened 2018-03-05 11:19 UTC
Maybe this is "as designed", but I noticed that Ben.Demystifier uses forward-slashes for path separators, and not backslashes, as the normal exception stack trace on Windows. It this intentional, for it to be the same across all platforms, or unintentional?

**Comment by johnrutherford** [comment] 2018-04-18 15:06
Yeah, I just noticed this too. It also replaces spaces in the path with "%20". So it's like the path is being formatted as a URL.

**Comment by onyxmaster** [comment] 2018-06-25 11:43
It converts the backtick characters to %60 too. It appears that "url" treatment didn't go so well for paths 😄

**Comment by bruno-garcia** [comment] 2021-01-03 22:26
~Can be closed:~
~Fixed on 0.1.4 PR #82~

The PR fixed something else:

`[InlineData(@"d:\Public Files+50%.Done\Src\Foo`1.cs", @"d:/Public Files+50%.Done/Src/Foo`1.cs", false)]`

**Closed as completed** 2021-01-03 22:42 UTC
Labels: bug

**Comment by onyxmaster** [comment] 2021-01-04 18:42
I would like to indicate that my PR (#82) was not intended to "fix" the path separators (I consider forward slashes as path separators as a feature, not a bug), it merely made them consistent along with proper handling of special characters.
